### ISSUE TITLE
gvr-immersivepedia crash on pause

### ISSUE THREAD

**Issue by liaxim** [gearvrf/GearVRf-Demos#219]
```
06-29 14:05:34.231 12393 12393 E AndroidRuntime: FATAL EXCEPTION: main
06-29 14:05:34.231 12393 12393 E AndroidRuntime: Process: com.samsung.android.gvr.sample, PID: 12393
06-29 14:05:34.231 12393 12393 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {com.samsung.android.gvr.sample/org.gearvrf.immersivepedia.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.gearvrf.GVRContext.getContext()' on a null object reference
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4659)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4618)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5465)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at android.app.ActivityThread.access$1200(ActivityThread.java:226)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1849)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7522)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.gearvrf.GVRContext.getContext()' on a null object reference
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at org.gearvrf.immersivepedia.Main.onPause(Main.java:102)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at org.gearvrf.immersivepedia.MainActivity.onPause(MainActivity.java:76)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:7033)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1339)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4645)
06-29 14:05:34.231 12393 12393 E AndroidRuntime: 	... 10 more
06-29 14:05:34.231 19615 20133 W ActivityManager:   Force finishing activity com.samsung.android.gvr.sample/org.gearvrf.immersivepedia.MainActivity
```

**Comment by liaxim** [comment]
@deepakrawat22 Please look at this.

**Comment by deepakrawat22** [comment]
@liaxim Thanks for finding the crash.

**Comment by liaxim** [comment]
Fixed by https://github.com/gearvrf/GearVRf-Demos/pull/220
