### ISSUE TITLE
Can't run apps in developer mode (without headset): library "libvrapi.so" not found

### ISSUE THREAD

**Issue by stpn** [gearvrf/GearVRf-Demos#375]
Hello,

I can run apps with headset, but in developer mode i get a ```"libvrapi.so" not found``` error.  How can I fix that? 

Full trace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.gearvrf.polyline, PID: 19036
                  java.lang.UnsatisfiedLinkError: dlopen failed: library "libvrapi.so" not found
                      at java.lang.Runtime.loadLibrary(Runtime.java:372)
                      at java.lang.System.loadLibrary(System.java:1076)
                      at org.gearvrf.GVRActivityNative.<clinit>(GVRActivityNative.java:25)
                      at org.gearvrf.GVRActivity.onCreate(GVRActivity.java:118)
                      at org.gearvrf.polyline.SampleActivity.onCreate(SampleActivity.java:27)
                      at android.app.Activity.performCreate(Activity.java:6876)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                      at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7229)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by liaxim** [comment]
@stpn Hello. Could you outline how you go about building the sample?
