### ISSUE TITLE
gvr-3dcursor: NPE

### ISSUE THREAD

**Issue by liaxim** [gearvrf/GearVRf-Demos#381]
Just normal use, tried to hit a button I believe.
```
12-02 09:18:16.205  2565  2692 E AndroidRuntime: FATAL EXCEPTION: GVRGazeEventHandlerThread
12-02 09:18:16.205  2565  2692 E AndroidRuntime: Process: org.gearvrf.io.cursor, PID: 2565
12-02 09:18:16.205  2565  2692 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.gearvrf.GVRSceneObject.getName()' on a null object reference
12-02 09:18:16.205  2565  2692 E AndroidRuntime: 	at org.gearvrf.io.cursor.CursorMain$5.onEvent(CursorMain.java:573)
12-02 09:18:16.205  2565  2692 E AndroidRuntime: 	at org.gearvrf.io.cursor3d.Cursor.dispatchCursorEvent(Cursor.java:683)
12-02 09:18:16.205  2565  2692 E AndroidRuntime: 	at org.gearvrf.io.cursor3d.Cursor.handleControllerEvent(Cursor.java:733)
12-02 09:18:16.205  2565  2692 E AndroidRuntime: 	at org.gearvrf.io.cursor3d.ObjectCursor$1.onEvent(ObjectCursor.java:127)
12-02 09:18:16.205  2565  2692 E AndroidRuntime: 	at org.gearvrf.GVRCursorController.update(GVRCursorController.java:620)
12-02 09:18:16.205  2565  2692 E AndroidRuntime: 	at org.gearvrf.GVRCursorController.setPosition(GVRCursorController.java:423)
12-02 09:18:16.205  2565  2692 E AndroidRuntime: 	at org.gearvrf.io.GVRGazeCursorController.access$101(GVRGazeCursorController.java:30)
12-02 09:18:16.205  2565  2692 E AndroidRuntime: 	at org.gearvrf.io.GVRGazeCursorController$EventHandlerThread$1.handleMessage(GVRGazeCursorController.java:249)
12-02 09:18:16.205  2565  2692 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
12-02 09:18:16.205  2565  2692 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
```

**Comment by parthmehta209** [comment]
I have added a fix for this: https://github.com/gearvrf/GearVRf-Demos/pull/385
