### ISSUE TITLE
android.view.Surface$OutOfResourcesException

### ISSUE THREAD

**Issue by Maqsood007** [gearvrf/GearVRf-Demos#387]
i am getting this issue while fast navigation between different scenes and my application gets crashed. it it any memory issues ? can any one help me ?
`Process: com.sensics.bubble1, PID: 29901
                                                                     android.view.Surface$OutOfResourcesException
                                                                         at android.view.Surface.nativeLockCanvas(Native Method)
                                                                         at android.view.Surface.lockCanvas(Surface.java:267)
                                                                         at org.gearvrf.scene_objects.GVRViewSceneObject.lockCanvas(GVRViewSceneObject.java:126)
                                                                         at org.gearvrf.scene_objects.view.GVRFrameLayout.draw(GVRFrameLayout.java:41)
                                                                         at android.view.View.draw(View.java:17381)
                                                                         at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
                                                                         at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
                                                                         at android.view.View.draw(View.java:17472)
                                                                         at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:3205)
                                                                         at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:3263)
                                                                         at android.view.ViewRootImpl.draw(ViewRootImpl.java:3167)
                                                                         at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2939)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2522)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7403)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:631)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:158)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by liaxim** [comment]
Looks like you might be having too many views. How many do you keep at the same time? Do you try to remove any when you navigate from one scene to another?

You might try to reduce the size of your views, e.g.:
```
        frameLayout = new GVRFrameLayout(this);
        frameLayout.setLayoutParams(new FrameLayout.LayoutParams(320, 320));
```
If you do that you may have to rework your layout.

**Comment by liaxim** [comment]
@Maqsood007 Did this help?
