### ISSUE TITLE
ListView On ItemClick error

### ISSUE THREAD

**Issue by pre2612** [gearvrf/GearVRf-Demos#414]
private OnItemClickListener itemClickListener = new OnItemClickListener() {
        @Override
        public void onItemClick(AdapterView<?> arg0, View arg1, int position,
                                long arg3) {
            final EventsApplication app = (EventsApplication) getApplicationContext();
            app.setMediaurl(lecturesList.get(position).getStreamingURL());

            Intent i = new Intent(getApplicationContext(), VideoActivity.class);
            i.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);

            // Add new Flag to start new Activity
            i.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            startActivity(i);
            finish();

        }
    };

E/ActivityThread: Activity org.gearvrf.events.EventsActivity has leaked ServiceConnection org.gearvrf.io.GVRAndroidWearTouchpad$1@d9b1716 that was originally bound here
                  android.app.ServiceConnectionLeaked: Activity org.gearvrf.events.EventsActivity has leaked ServiceConnection org.gearvrf.io.GVRAndroidWearTouchpad$1@d9b1716 that was originally bound here
                      at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1204)
                      at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1098)
                      at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1412)
                      at android.app.ContextImpl.bindService(ContextImpl.java:1395)
                      at android.content.ContextWrapper.bindService(ContextWrapper.java:632)
                      at org.gearvrf.io.GVRAndroidWearTouchpad.connectToWatch(GVRAndroidWearTouchpad.java:101)
                      at org.gearvrf.io.GVRAndroidWearTouchpad.<init>(GVRAndroidWearTouchpad.java:59)
                      at org.gearvrf.io.GVRInputManager.<init>(GVRInputManager.java:98)
                      at org.gearvrf.GVRInputManagerImpl.<init>(GVRInputManagerImpl.java:43)
                      at org.gearvrf.GVRViewManager.<init>(GVRViewManager.java:60)
                      at org.gearvrf.OvrViewManager.<init>(OvrViewManager.java:101)
                      at org.gearvrf.OvrActivityDelegate.makeViewManager(OvrActivityDelegate.java:47)
                      at org.gearvrf.GVRActivity.setMain(GVRActivity.java:250)
                      at org.gearvrf.events.EventsActivity.onCreate(EventsActivity.java:103)
                      at android.app.Activity.performCreate(Activity.java:6876)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                      at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:158)
                      at android.app.ActivityThread.main(ActivityThread.java:7229)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by liaxim** [comment]
@pre2612 Thanks for reporting the problem. We are aware of it and tracking it as https://github.com/Samsung/GearVRf/issues/1024. The plan is to fix it in the next version.

Other than the logcat printout are you seeing anything else?

**Comment by liaxim** [comment]
Fix merged
