### ISSUE TITLE
Error Expoplayer on Video url instead of downloading

### ISSUE THREAD

**Issue by pre2612** [gearvrf/GearVRf-Demos#415]
E/ExoPlayerImplInternal: Internal track renderer error.
                         com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, MediaFormat(1, video/avc, -1, 98901, 640, 480, 0, 1.0, -1, -1, null, 2731132000, false, -1, -1, -1, -1, -1)
                             at com.google.android.exoplayer.MediaCodecTrackRenderer.notifyAndThrowDecoderInitError(MediaCodecTrackRenderer.java:427)
                             at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:413)
                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.setSurface(MediaCodecVideoTrackRenderer.java:314)
                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.handleMessage(MediaCodecVideoTrackRenderer.java:295)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:587)
                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:227)
                             at android.os.Handler.dispatchMessage(Handler.java:98)
                             at android.os.Looper.loop(Looper.java:158)
                             at android.os.HandlerThread.run(HandlerThread.java:61)
                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                          Caused by: com.google.android.exoplayer.MediaCodecTrackRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, MediaFormat(1, video/avc, -1, 98901, 640, 480, 0, 1.0, -1, -1, null, 2731132000, false, -1, -1, -1, -1, -1)
                             at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:413) 
                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.setSurface(MediaCodecVideoTrackRenderer.java:314) 
                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.handleMessage(MediaCodecVideoTrackRenderer.java:295) 
                             at com.google.android.exoplayer.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:587) 
                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:227) 
                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                             at android.os.Looper.loop(Looper.java:158) 
                             at android.os.HandlerThread.run(HandlerThread.java:61) 
                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
                          Caused by: java.lang.IllegalArgumentException: The surface has been released
                             at android.media.MediaCodec.native_configure(Native Method)
                             at android.media.MediaCodec.configure(MediaCodec.java:1778)
                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.configureCodec(MediaCodecVideoTrackRenderer.java:328)
                             at com.google.android.exoplayer.MediaCodecTrackRenderer.maybeInitCodec(MediaCodecTrackRenderer.java:402)
                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.setSurface(MediaCodecVideoTrackRenderer.java:314) 
                             at com.google.android.exoplayer.MediaCodecVideoTrackRenderer.handleMessage(MediaCodecVideoTrackRenderer.java:295) 
                             at com.google.android.exoplayer.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:587) 
                             at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:227) 
                             at android.os.Handler.dispatchMessage(Handler.java:98) 
                             at android.os.Looper.loop(Looper.java:158) 
                             at android.os.HandlerThread.run(HandlerThread.java:61) 
                             at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by liaxim** [comment]
@pre2612 Could you please give us some context? What are you doing? Are you trying to run one of our demos? Which one? Thanks.

**Comment by pre2612** [comment]
gvr-video demo but with a url from api instead of downloaded video.

**Comment by pre2612** [comment]
Thanks so much for helping out!

**Comment by tresvecesseis** [comment]
I use the GearVRf for online video changing the AssetDataSource with a DefaultUriDataSource (that also supports asset:// URIs):

```
-        final AssetDataSource dataSource = new AssetDataSource(context);
+        final DataSource dataSource = new DefaultUriDataSource(context, "Mozilla 5.0");
```

In fact, I should submit a patch with this change as is much more convenient as it support a wider set of URIs

**Comment by liaxim** [comment]
@tresvecesseis Thanks for the tip. I made the change and verified that playing from url works. https://github.com/gearvrf/GearVRf-Demos/pull/425

**Comment by pre2612** [comment]
This change should go into Moviemanager.java file:

 String userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:40.0) Gecko/20100101 Firefox/40.0";
        String mediaUrl = "http://html5demos.com/assets/dizzy.mp4";

        DataSource dataSource = new DefaultUriDataSource(context, null, userAgent);
        final ExtractorSampleSource sampleSource = new ExtractorSampleSource(Uri.parse(mediaUrl),
                dataSource, new DefaultAllocator(64 * 1024), 64 * 1024 * 256);

Could someone help where this needs to be placed?

**Comment by liaxim** [comment]
@pre2612 This is pretty much what I did in https://github.com/gearvrf/GearVRf-Demos/pull/425.

**Comment by liaxim** [comment]
Change merged
